name: Cleanup docker containers

on: [pull_request]

jobs:
  build:
    name: Utf√∏r verdikjede-test
    runs-on: ubuntu-latest

    steps:
      - name: Rensk docker images
        run: |
          docker system df
